basePath: /
definitions:
  dto.CreateDeviceRequest:
    properties:
      brand:
        example: Motorola
        type: string
      name:
        example: Moto G100
        type: string
      state:
        enum:
        - available
        - in-use
        - inactive
        example: available
        type: string
    required:
    - brand
    - name
    - state
    type: object
  dto.DeviceResponse:
    properties:
      brand:
        example: Apple
        type: string
      created_at:
        example: "2025-08-31T21:00:00Z"
        type: string
      deleted_at:
        example: "null"
        type: string
      id:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
      name:
        example: iPhone 13
        type: string
      state:
        example: available
        type: string
      updated_at:
        example: "2025-08-31T21:00:00Z"
        type: string
    type: object
  errors.DefaultErrorResult:
    properties:
      error:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: tiago482@gmail.com
    url: https://tiagos4ntos.github.io
  description: API for managing an inventory of mobile devices.
  license:
    name: APACHE 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Device Manager API
  version: 0.0.1-beta
paths:
  /devices:
    get:
      consumes:
      - application/json
      description: Get all devices
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.DeviceResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.DefaultErrorResult'
      summary: List devices
      tags:
      - devices
    post:
      consumes:
      - application/json
      description: Registers a new device
      parameters:
      - description: Device payload
        in: body
        name: device
        required: true
        schema:
          $ref: '#/definitions/dto.CreateDeviceRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.DeviceResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.DefaultErrorResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.DefaultErrorResult'
      summary: Create a new device
      tags:
      - devices
  /devices/{id}:
    delete:
      description: Removes a device by ID
      parameters:
      - description: Device ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.DefaultErrorResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.DefaultErrorResult'
      summary: Delete a device
      tags:
      - devices
    get:
      description: Returns a single device by its ID
      parameters:
      - description: Device ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.DeviceResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.DefaultErrorResult'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.DefaultErrorResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.DefaultErrorResult'
      summary: Get device by ID
      tags:
      - devices
swagger: "2.0"
